# Generated by Django 4.0.4 on 2022-05-18 00:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id_cachorro', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('porte', models.CharField(max_length=255)),
                ('raca', models.CharField(max_length=255)),
                ('idade', models.IntegerField()),
                ('dono', models.CharField(max_length=255)),
            ],
        ),
    ]
